name: my_life_calendar_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  dashed_circular_progress_bar: ^0.0.6
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  freezed_annotation: ^2.4.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  scroll_date_picker: ^3.8.0
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  timeline_tile: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: null
  hive_generator: ^2.0.1
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/gif/loading_gif.gif
